#!/usr/bin/env bash

if /data/django/service/status_gm_service > /dev/null; then
    echo "already running (pid=`cat /data/django/service/logs/service_pid`)"
    exit 3
else
    unset noclobber
    cd /data/django/dashboard/server/monitoringsite
    rm -rf /data/django/service/logs/kill
    nohup python manage.py runcollector production > /data/django/service/logs/nohup.out 2>&1  &
    echo $! > /data/django/service/logs/service_pid
    echo 'gangamon service started'
fi
